### ISSUE TITLE
Suggest to remove unused CSS rules?

### ISSUE THREAD

**Issue by arthurvr** [zenorocha/browser-diet#267]
Removing unused CSS rules to shave out bytes is best-practice. Using [`uncss`](https://github.com/giakki/uncss), for example.

**Comment by mkautzmann** [comment]
+1 with a comment: you need to be careful not to add those rules in the first place, but if you are using a framework like Bootstrap it could be a good practice. Also it's important to notice that uncss can cause problems if you load new content to the DOM that uses the lines previously removed.

**Comment by zenorocha** [comment]
+1
