### ISSUE TITLE
Inconsistência visual na barra do topo da página

### ISSUE THREAD

**Issue by ciceropablo** [zenorocha/browser-diet#270]
Percebi uma quebra na barra do topo da página quando entrei no site em polonês (pl) e espanhol (es).
Esse problema entrou aqui 31a76649d7c7f7d40caff0debe584e9cdf26e800, mas não entendi por quê. Tem algum motivo @zenorocha?

![print](https://cloud.githubusercontent.com/assets/174275/6860070/60cb0626-d401-11e4-990a-bd5cd9ac7d76.jpg)

**Comment by zenorocha** [comment]
Isso é um bug, pode mandar um PR corrigindo?

**Comment by ciceropablo** [comment]
Feito! #269
