### ISSUE TITLE
Quebra no conteúdo de destaque principal em telas menores

### ISSUE THREAD

**Issue by ciceropablo** [zenorocha/browser-diet#271]
Acontece uma quebra no conteúdo de destaque principal `div.intro` em telas menores, largura entre 480 e 320. Esse bug acaba variando conforme o idioma, por conta do texto na barra do topo da página `div#top-bar`.

Percebi que esse bug nos leva a outro problema que é o componente de seleção do idioma `div#language-picker`, que possui `375px` de largura e vai acabar criando um scroll horizontal.

Talvez esse componente tenha que ser redesenhado. :weary:

**iPhone 5 (320 x 568)**
![print](https://cloud.githubusercontent.com/assets/174275/6863538/807fba1c-d432-11e4-807d-9830462ae291.jpg)

**Comment by zenorocha** [comment]
Fixed on #269
