### ISSUE TITLE
中文版中的“优化你的图片”

### ISSUE THREAD

**Issue by kujian** [zenorocha/browser-diet#274]
另一种优化图片的方式是，以图片质量为代价进行压缩。我们称之为有损压缩。举例来说，当你”到处“一个JPEG图片时，你可以选择导出的图片质量（从0到100）。考虑到性能，总是选择可接受范围内的最低值。在PNG图片中，另一个常见的有损技术是减少颜色数量，或者将PNG-24格式转换为PNG-8格式。

这里”到处“写错了，应该是"导出“。

**Comment by fordlee404** [comment]
relative to PR #275

**Comment by zenorocha** [comment]
Merged #275.

**Comment by zenorocha** [comment]
Thanks @fordlee404!

**Comment by fordlee404** [comment]
谢谢 @kujian
