### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by dsoldera** [zenorocha/browser-diet#282]
Ola,

Não estou conseguindo instalar o projeto. Ocorre o seguinte erro:

![error-browser-diet](https://cloud.githubusercontent.com/assets/11474555/10853583/f444abc4-7f1d-11e5-918e-bfc56d150e6f.png)

**Comment by zenorocha** [comment]
Qual sua versão de node e npm?

**Comment by dsoldera** [comment]
Node version 0.12.7
NPM version 2.11.3

**Comment by mkautzmann** [comment]
Você pode atualizar seu Node para a versão estável `v4`?

**Comment by dsoldera** [comment]
É realmente necessário?? E que eu trabalho em projeto que precisa dessa versão antiga.

Caso precise mesmo, eu indicaria colocar na documentação a restrição (uso do node na versão x).

Obrigada pela ajuda. =)

Abs,

**Comment by mkautzmann** [comment]
Espera aí, talvez seu erro não seja relacionado ao Node. Agora vi que você já está rodando o `docpad run`. Vou tentar reproduzir seu cenário aqui.

**Comment by dsoldera** [comment]
Sim, o erro acontece somente quando eu rodo o docpad run. Antes disso, todos os passos ocorrem com sucesso.

**Comment by zenorocha** [comment]
@dsoldera você pode usar n ou nvm para gerenciar diferentes versões de node

**Comment by dsoldera** [comment]
@zenorocha Eu vou instalar e fazer alguns testes. 

Obrigada.

**Comment by mkautzmann** [comment]
@dsoldera Pode confirmar que funciona com a `v4`? Acredito que o problema não é relacionado ao Node.JS diretamente, estou conseguindo rodar com a versão `0.12.7`.

Se quiser instalar só para testar recomendo as dicas do @zenorocha e usar `n` ou `nvm`.

**Comment by mkautzmann** [comment]
Para ser mais exato acredito que o problema está relacionado com este issue:

https://github.com/docpad/docpad/issues/813

Além disso parece só se manifestar em ambiente Windows, o problema parece ser que o script do docpad não acha a localização do grunt localmente instalado.

Se você confirmar que também não funciona no Node `v4` eu posso pesquisar melhor um fix para isso.

**Comment by zenorocha** [comment]
@mkautzmann, estou super aberto para remover a dependência de Grunt para Gulp se quiser atacar isso

**Comment by mkautzmann** [comment]
É possível, é questão de preferência mas acredito que até dá pra manter o Grunt atualizando o plugin dele para docpad. Vou montar um ambiente Windows para testes e dar uma estudada nas possíveis opções. Mando uma PR se encontrar uma solução.

**Comment by dsoldera** [comment]
Olá Pessoal,

Eu instalei uma versão mais nova do node.js - 4.2.1, refiz todo processo de instalação e o erro persiste. 

Verifiquei se seria erro de permissão do docpad, já dei permissão total ao node.js por ser Windows e mesmo assim ainda persiste o erro quando rodo o comando docpad run. Tambem pedi para instalar globalmente a ultima versão do grunt. 

Fico no aguardo de alguma dica de solução.

Obrigada pela ajuda.

**Comment by mkautzmann** [comment]
Sim, o problema é o que eu esperava então. Plugin do grunt para `docpad` em ambiente Windows. Obrigado @dsoldera. Vou analisar isso e enviar uma PR com o fix.

**Comment by zenorocha** [comment]
@mkautzmann pode substituir o Grunt ou então tirar ele do processo de build do Docpad?

**Comment by mkautzmann** [comment]
Sim, estou mesmo vendo isso.

**Comment by mkautzmann** [comment]
Mandei PR, parece OK. Dê uma olhada.

**Comment by mkautzmann** [comment]
Parece que resolvemos o problema @dsoldera. Se puder, passa um feedback se está OK agora a instalação. Valeu!

**Comment by dsoldera** [comment]
Olá. Eu irei fazer mais testes a noite e te falo. 

Obrigada.

Abs.

**Comment by dsoldera** [comment]
@mkautzmann testei. Deu certinho agora a instalação.

Obrigada mais uma vez.

Abs,

**Comment by zenorocha** [comment]
You-are-the-man @mkautzmann!
