### ISSUE TITLE
Many google links in wiki force pt-BR language

### ISSUE THREAD

**Issue by Cybermaxs** [zenorocha/browser-diet#297]
Many google links in wiki force pt-BR language.
eg. Google Speed - Minify HTML => https://developers.google.com/speed/docs/insights/PrioritizeVisibleContent?hl=pt-BR#MinifyHTML.

It will be better -from my point of view- to remove hl=pt-BR from all links and keep english as the default language(Google may also redirects depending on user settings)

**Comment by zenorocha** [comment]
Fixed! Thanks for reporting @Cybermaxs :)
